// nextjs-frontend/components/PasswordStrengthMeter.tsx
"use client";

import clsx from "clsx";
import { useMemo } from "react";

enum PasswordStrength {
  TooShort = 0,
  Weak = 1,
  Good = 2,
  Strong = 3,
  VeryStrong = 4,
}

function calcStrength(password: string): PasswordStrength {
  if (!password) {
    return PasswordStrength.TooShort;
  }

  if (password.length < 8) {
    return PasswordStrength.Weak;
  }

  if (password.length < 12) {
    return PasswordStrength.Good;
  }

  if (password.length < 16) {
    return PasswordStrength.Strong;
  }

  return PasswordStrength.VeryStrong;
}

function strengthText(passwordStrength: PasswordStrength): string {
  switch (passwordStrength) {
    case PasswordStrength.TooShort:
      return "Too short";

    case PasswordStrength.Weak:
      return "Weak";

    case PasswordStrength.Good:
      return "Good";

    case PasswordStrength.Strong:
      return "Strong";

    case PasswordStrength.VeryStrong:
      return "Very strong";

    default:
      return "";
  }
}

export type PasswordStrengthMeterProps = {
  password: string;
};

export default function PasswordStrengthMeter({
  password,
}: PasswordStrengthMeterProps) {
  const calculatedPasswordStrength = useMemo<number>(() => {
    return calcStrength(password);
  }, [password]);

  return (
    <div className="flex h-4 items-center gap-1">
      <Stripe isActive={calculatedPasswordStrength >= PasswordStrength.Weak} />
      <Stripe isActive={calculatedPasswordStrength >= PasswordStrength.Good} />
      <Stripe
        isActive={calculatedPasswordStrength >= PasswordStrength.Strong}
      />
      <Stripe
        isActive={calculatedPasswordStrength >= PasswordStrength.VeryStrong}
      />

      {calculatedPasswordStrength > PasswordStrength.TooShort && (
        <div className="ml-1 text-xs">
          {strengthText(calculatedPasswordStrength)}
        </div>
      )}
    </div>
  );
}

type StripProps = {
  isActive: boolean;
};

function Stripe({ isActive }: StripProps) {
  return (
    <div
      className={`
        h-1
        w-12
        rounded-full

        ${clsx({
          "bg-zinc-800": isActive,
          "bg-gray-200": !isActive,
        })}
      `}
    ></div>
  );
}

// angular-frontend/src/app/components/password-strength-meter/password-strength-meter.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

enum PasswordStrength {
  TooShort = 0,
  Weak = 1,
  Good = 2,
  Strong = 3,
  VeryStrong = 4,
}

@Component({
  selector: 'app-password-strength-meter',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './password-strength-meter.component.html',
  styleUrls: ['./password-strength-meter.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PasswordStrengthMeterComponent {
  @Input()
  password?: string;

  // making enum accessible to component
  PasswordStrength = PasswordStrength;

  get strength(): PasswordStrength {
    if (!this.password) {
      return this.PasswordStrength.TooShort;
    }

    if (this.password.length < 8) {
      return this.PasswordStrength.Weak;
    }

    if (this.password.length < 12) {
      return this.PasswordStrength.Good;
    }

    if (this.password.length < 16) {
      return this.PasswordStrength.Strong;
    }

    return this.PasswordStrength.VeryStrong;
  }

  get strengthText(): string {
    switch (this.strength) {
      case this.PasswordStrength.TooShort:
        return 'Too short';

      case this.PasswordStrength.Weak:
        return 'Weak';

      case this.PasswordStrength.Good:
        return 'Good';

      case this.PasswordStrength.Strong:
        return 'Strong';

      case this.PasswordStrength.VeryStrong:
        return 'Very strong';

      default:
        return '';
    }
  }
}

<div
  class="stripe"
  [class.active]="strength >= PasswordStrength.Weak"
></div>

<div
  class="stripe"
  [class.active]="strength >= PasswordStrength.Good"
></div>

<div
  class="stripe"
  [class.active]="strength >= PasswordStrength.Strong"
></div>

<div
  class="stripe"
  [class.active]="strength >= PasswordStrength.VeryStrong"
></div>

<div class="text-indicator">
  {{ strengthText }}
</div>
