// nextjs-frontend/components/Header.tsx
import { Button } from "./ui/button";

export default function Header() {
  return (
    <header className="flex h-[75px] w-full flex-row items-center gap-5 bg-white px-7 shadow-md">
      <h1 className="cursor-pointer text-xl font-bold">Dontsueme</h1>

      <div className="text-sm hover:cursor-pointer hover:text-violet-600">
        Categories
      </div>

      <div className="flex flex-grow flex-row items-center gap-2 rounded-full border border-gray-800 bg-gray-100 px-4 text-sm  focus:border-violet-700">
        <span className="material-icons-outlined text-gray-500">search</span>

        <input
          className="flex h-[48px] w-full bg-transparent placeholder-gray-500 outline-none"
          placeholder="Search for anything"
        />
      </div>

      <div className="text-sm hover:cursor-pointer hover:text-violet-600">
        Teach on Udemy
      </div>

      <Button className="material-icons-outlined" variant={"icon"}>
        shopping_cart
      </Button>

      <div className="flex flex-row items-center gap-2">
        <Button variant={"outline"}>Log in</Button>

        <Button>Sign Up</Button>

        <Button className="material-icons-outlined" variant={"outlineIcon"}>
          language
        </Button>
      </div>
    </header>
  );
}

// angular-frontend/src/app/components/header/header.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeaderComponent {}

<h3 class="logo">Dontsueme</h3>

<div class="clickable">Categories</div>

<div class="search-bar">
  <span class="material-icons"> search </span>

  <span>Search for anything</span>
</div>

<div class="clickable">Udemy Business</div>

<div class="clickable">Teach On Udemy</div>

<div style="display: flex; gap: 0.6rem">
  <button class="icon-button">
    <span class="material-icons-outlined"> shopping_cart </span>
  </button>

  <button class="white">Log in</button>

  <button class="black">Sign Up</button>

  <button class="white icon-button">
    <span class="material-icons-outlined"> language </span>
  </button>
</div>
